services:
  # Frontend Service (React + Nginx)
  frontend:
    build:
      context: ./frontend
    container_name: frontend_container
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend
    deploy:
      resources:
        reservations:
          memory: "256M"

  # Backend Service (Node/Express)
  backend:
    build:
      context: ./backend
    container_name: backend_container
    ports:
      - "5000:5000"
    networks:
      - app-network
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NODE_ENV=production
    deploy:
      resources:
        reservations:
          memory: "512M"

# Shared network between frontend and backend
networks:
  app-network:
    driver: bridge